### ISSUE TITLE
TypeError when trying to use `tokenize()` to highlight code

### ISSUE THREAD

**Issue by willdurand** [otakustay/react-diff-view#38]
Hi,

I am not sure how much information I can provide but I am not able to make the syntax highlighting work with the version `2.0` of this lib. I use `tokenize()` and the following `options`:

```js
    const options = {
      highlight: true,
      language: 'js',
      refractor: refractor,
    };
```

`refractor` is imported via:

```js
import refractor from 'refractor';
```

Simply logging the result of `tokenize()` fails:

```js
console.log({ tokens: tokenize(hunks, options) });
```

If I set `highlight` to `false` in `options`, I get the `tokens`, but with highlighting enabled, I also get a `TypeError`:

```
i is not a function
```

Because I use the npm package, I don't have more information. I tried to debug and I know that it works until after this line: https://github.com/otakustay/react-diff-view/blob/6aa5399c52392e19f7f8fbe4af17b374b4339862/src/tokenize/index.js#L15. The `toTokenTrees` returns similar results with `highlight` set to `true` or `false`.

I am hoping that you might have ideas. 🤞 

Thanks!

**Comment by otakustay** [comment]
Can you provide the diff text provided to component so I can try to reproduce the inputs of `tokenize` function?

**Comment by willdurand** [comment]
Yes, it is this one: https://github.com/mozilla/addons-code-manager/blob/9e9239b7526d9576ff8d17836e8fdc7e5048164c/src/components/DiffView/fixtures/diffWithDeletions.tsx

I just cloned and `yarn link`'ed this lib, compiled without `terser()` and... it works. There is no errors 🤔

**Comment by willdurand** [comment]
If I install `react-diff-view` with `yarn add react-diff-view`, the error is back.

**Comment by willdurand** [comment]
> I just cloned and `yarn link`'ed this lib, compiled without `terser()` and... it works. There is no errors 🤔

ah oops, no. I was a few commits behind `master`. So there is a regression between `4bca86c` and `2.0.1` I believe.

**Comment by willdurand** [comment]
Here is a more accurate error:

```
Hooks can only be called inside the body of a function component.
```

**Comment by otakustay** [comment]
2.0.1 release should not be using hooks itself, are you using the master branch to build this lib yourself, or just installing 2.0.1 from npm?

**Comment by willdurand** [comment]
> 2.0.1 release should not be using hooks itself, are you using the master branch to build this lib yourself, or just installing 2.0.1 from npm?

I use `2.0.1` from npm and I tried to use `master` locally (using `yarn link`) to get more information (`i is not a function` not being super helpful).

**Comment by willdurand** [comment]
I just tried `8bb9feebd945fa3fd4b81ea415b4923485ca1d76` and it works.

**Comment by otakustay** [comment]
Got it, I will try to reproduce this issue in 2.0.1 and further mark it as a regression test case

**Comment by willdurand** [comment]
One more thing: https://github.com/otakustay/react-diff-view/commit/8bb9feebd945fa3fd4b81ea415b4923485ca1d76 works locally when compiled without `terser()` but the error is back when I re-enable `terser()` in `rollup.js`. huh.

**Comment by willdurand** [comment]
This recent issue might be related: https://github.com/terser-js/terser/issues/292, but not sure.

**Comment by willdurand** [comment]
Yep, looks like a mangling issue because this patch produces a correct build:

```diff
diff --git a/rollup.js b/rollup.js
index 83d48d7..98dbba6 100644
--- a/rollup.js
+++ b/rollup.js
@@ -19,7 +19,7 @@ const inputOptions = {
         autoExternal({dependencies: false}),
         sourcemaps(),
         babel({exclude: 'node_modules/**'}),
-        terser()
+        terser({ mangle: false })
     ]
 };
```

Fun!

**Comment by otakustay** [comment]
Can you further provide your debugging browser? mangling issues can behave differently in different js engines.

For quick fix, I think I can just provide a patch version with `mangle` option disabled, would it help you currently?

**Comment by willdurand** [comment]
> Can you further provide your debugging browser? mangling issues can behave differently in different js engines.

I tried in both Firefox and Chrome (although I mostly use Chrome).

> For quick fix, I think I can just provide a patch version with `mangle` option disabled, would it help you currently?

That would be perfect ❤️

**Comment by otakustay** [comment]
You could try `2.0.2` to validate the issue, this is a patch version based on `2.0.1` only changing the `mangle` option of terser

For the reason that `master` is already "polluted" with some further refractors, `2.0.2` is only published via my own computer, will have `mangle` option disabled in master in later commits.

Since mangling issue will be really hard to debug and it's quite late in China, if `2.0.2` fixes your issue, I may dig into it some hours later, it could be nice if you can provide me a codesandbox reproducing your issue, I cannot reproduce it in https://codesandbox.io/s/mz126y9k79 using `2.0.1`

**Comment by willdurand** [comment]
Thanks a lot and sorry for keeping you awake at night. `2.0.2` works fine! I will try to change your codesandbox to reproduce the issue, thanks!

**Comment by willdurand** [comment]
Hi, version `2.1.1` is affected by this issue again 😥

**Comment by otakustay** [comment]
My fault, failed to merge this fix to master, `2.1.2` should fix
